package sg.com.stellarstudios.imser.entity;


/**
 * Country generated by MyEclipse Persistence Tools
 */

public class Country extends sg.com.stellarstudios.imser.entity.BaseEntity
		implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	// Constructors

	/** default constructor */
	public Country() {
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    public void setId(Object id) {
    	if (id.getClass().isAssignableFrom(String[].class)) this.id = new Integer(((String[])id)[0]);
    	else this.id = (Integer)id;
    }
    
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}