package sg.com.stellarstudios.imser.entity;

import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * User generated by MyEclipse Persistence Tools
 */

public class User extends sg.com.stellarstudios.imser.entity.BaseEntity
		implements java.io.Serializable {

	// Fields

	private Integer id;

	private String email;

	private String password;

	private String authorizedModules;

	private Set userRegistrations = new HashSet(0);
	
	// not persisted
	
    private Map authorizedModulesBoolean;
    
    private Boolean rememberLogin;

	// Constructors

	/** default constructor */
	public User() {
		authorizedModulesBoolean = new LinkedHashMap();
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    public void setId(Object id) {
    	if (id.getClass().isAssignableFrom(String[].class)) this.id = new Integer(((String[])id)[0]);
    	else this.id = (Integer)id;
    }
    
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAuthorizedModules() {
		return this.authorizedModules;
	}

	public void setAuthorizedModules(String authorizedModules) {
		this.authorizedModules = authorizedModules;
	}

	public Set getUserRegistrations() {
		return this.userRegistrations;
	}

	public UserRegistration getUserRegistration() {
		return (UserRegistration) this.userRegistrations.iterator().next();
	}
	
	public void setUserRegistration(Object obj) { }
	
	public void setUserRegistrations(Set userRegistrations) {
		this.userRegistrations = userRegistrations;
	}

	public Map getAuthorizedModulesBoolean() {
		return authorizedModulesBoolean;
	}

	public void setAuthorizedModulesBoolean(Map authorizedModulesBoolean) {
		this.authorizedModulesBoolean = authorizedModulesBoolean;
	}

	public Boolean getRememberLogin() {
		return rememberLogin;
	}

	public void setRememberLogin(Boolean rememberLogin) {
		this.rememberLogin = rememberLogin;
	}
}